# ~/.zshrc — Dotfiles Citadel (WSL2 / Ubuntu 24.04)
# Managed by: https://github.com/geekedsilicon/dotfiles
# Do NOT edit this file directly — edit wsl/.zshrc in the repository instead.

# ---------------------------------------------------------------------------
# Zinit plugin manager (fast, compiled)
# ---------------------------------------------------------------------------
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d "$ZINIT_HOME" ] && mkdir -p "$(dirname "$ZINIT_HOME")" && \
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

# Syntax highlighting + autosuggestions (lazy-loaded for fast start-up)
zinit ice wait lucid
zinit light zsh-users/zsh-syntax-highlighting

zinit ice wait lucid
zinit light zsh-users/zsh-autosuggestions

# ---------------------------------------------------------------------------
# Starship prompt (cross-shell, low-overhead)
# ---------------------------------------------------------------------------
export STARSHIP_CONFIG="$HOME/.config/starship.toml"
command -v starship &>/dev/null && eval "$(starship init zsh)"

# ---------------------------------------------------------------------------
# Path
# ---------------------------------------------------------------------------
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------
export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less -FRX"
export LANG="en_US.UTF-8"

# ---------------------------------------------------------------------------
# History
# ---------------------------------------------------------------------------
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# ---------------------------------------------------------------------------
# Aliases
# ---------------------------------------------------------------------------
alias ll="ls -lAh --color=auto"
alias la="ls -A --color=auto"
alias grep="grep --color=auto"
alias vim="nvim"
alias g="git"
alias dc="docker compose"

# WSL-specific: open Windows Explorer in current directory
alias explorer='explorer.exe .'

# ---------------------------------------------------------------------------
# WSL2 display / WSLENV passthrough
# ---------------------------------------------------------------------------
export WSLENV=USERPROFILE/p:APPDATA/p
